version: '2.1'

volumes:
  ipfs_staging:
  ipfs_data:

services:

  ipfs:
    build:
      context: ./go-ipfs
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    volumes:
      - 'ipfs_data:/data/ipfs' # Only required if using PERSISTENT flag (see below)
      - 'ipfs_staging:/export' # Only required if using PERSISTENT flag (see below)
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    labels:
      # io.balena.features.balena-socket: '1'
      # io.balena.features.kernel-modules: '1'
      # io.balena.features.firmware: '1'
      # io.balena.features.dbus: '1'
      # io.balena.features.sysfs: '1'
      # io.balena.features.procfs: '1'
      # io.balena.features.journal-logs: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      # io.balena.update.strategy: download-then-kill
      # io.balena.update.handover-timeout: ''
